Song.destroy_all
Artist.destroy_all

#---- Artists ----

velvet_underground = Artist.create(name: "The Velvet Underground", image_url: "http://res.cloudinary.com/ewoudtm/image/upload/v1489935423/codaisseurify/velvet_underground/velvet-underground-the-50f1828d7c7f6.jpg")
smashing_pumpkins = Artist.create(name: "The Smashing Pumpkins", image_url: "http://res.cloudinary.com/ewoudtm/image/upload/v1489884851/codaisseurify/smashing_pumpkins/smashing_pumpkins.jpg")
nirvana = Artist.create(name: "Nirvana", image_url: "http://res.cloudinary.com/ewoudtm/image/upload/v1489884892/codaisseurify/nirvana/nirvana.jpg")
green_day = Artist.create(name: "Green Day", image_url: "http://res.cloudinary.com/ewoudtm/image/upload/v1489884942/codaisseurify/green_day/green_day2.jpg")
rammstein = Artist.create(name: "Rammstein", image_url: "http://res.cloudinary.com/ewoudtm/image/upload/v1489935902/codaisseurify/rammstein/Rammstein_LIFAD.jpg")
nick_cave_bad_seeds = Artist.create(name: "Nick Cave & The Bad Seeds", image_url: "http://res.cloudinary.com/ewoudtm/image/upload/v1489884921/codaisseurify/nick_cave/nick-cave.jpg")
david_bowie = Artist.create(name: "David Bowie", image_url: "http://res.cloudinary.com/ewoudtm/image/upload/v1489884961/codaisseurify/david_bowie/David-Bowie-Bonds-Treveri-Capital-Intellectual-Property-Debt-Finance.jpg")
depeche_mode = Artist.create(name: "Depeche Mode", image_url: "http://res.cloudinary.com/ewoudtm/image/upload/v1489936087/codaisseurify/depeche_mode/depeche-mode.jpg")
joy_division = Artist.create(name: "Joy Division", image_url: "http://res.cloudinary.com/ewoudtm/image/upload/v1489936297/codaisseurify/joy_division/joy-division-pic.jpg")
the_cure = Artist.create(name: "The Cure", image_url: "http://res.cloudinary.com/ewoudtm/image/upload/v1489884805/codaisseurify/cure/the_cure.jpg")
bloc_party = Artist.create(name: "Bloc Party", image_url: "http://res.cloudinary.com/ewoudtm/image/upload/v1489884984/codaisseurify/bloc_party/bloc-party.jpg")
the_verve = Artist.create(name: "The Verve", image_url: "http://res.cloudinary.com/ewoudtm/image/upload/v1489884774/codaisseurify/verve/1998NMEAwardsVerve021111.jpg")
# #---- Photos ----
#
# photo_velvet_underground = Photo.create(image: "http://res.cloudinary.com/ewoudtm/image/upload/v1489935423/codaisseurify/velvet_underground/velvet-underground-the-50f1828d7c7f6.jpg", artist: velvet_underground)
# photo_smashing_pumpkins = Photo.create(image: "http://res.cloudinary.com/ewoudtm/image/upload/v1489884851/codaisseurify/smashing_pumpkins/smashing_pumpkins.jpg", artist: smashing_pumpkins)
# photo1 = Photo.create(image: "http://res.cloudinary.com/ewoudtm/image/upload/v1489884892/codaisseurify/nirvana/nirvana.jpg", artist: nirvana)
# photo_green_day = Photo.create(image: "http://res.cloudinary.com/ewoudtm/image/upload/v1489884942/codaisseurify/green_day/green_day2.jpg", artist: green_day)
# photo_rammstein = Photo.create(image: "http://res.cloudinary.com/ewoudtm/image/upload/v1489935902/codaisseurify/rammstein/Rammstein_LIFAD.jpg", artist: rammstein)
# photo_nick_cave_bad_seeds = Photo.create(image: "http://res.cloudinary.com/ewoudtm/image/upload/v1489884921/codaisseurify/nick_cave/nick-cave.jpg", artist: nick_cave_bad_seeds)
# photo_david_bowie = Photo.create(image: "http://res.cloudinary.com/ewoudtm/image/upload/v1489884961/codaisseurify/david_bowie/David-Bowie-Bonds-Treveri-Capital-Intellectual-Property-Debt-Finance.jpg", artist: david_bowie)
# photo_depeche_mode = Photo.create(image: "http://res.cloudinary.com/ewoudtm/image/upload/v1489936087/codaisseurify/depeche_mode/depeche-mode.jpg", artist: depeche_mode)
# photo_joy_division = Photo.create(image: "http://res.cloudinary.com/ewoudtm/image/upload/v1489936297/codaisseurify/joy_division/joy-division-pic.jpg", artist: joy_division)
# photo_the_cure = Photo.create(image: "http://res.cloudinary.com/ewoudtm/image/upload/v1489884805/codaisseurify/cure/the_cure.jpg", artist: the_cure)
# photo_bloc_party = Photo.create(image: "http://res.cloudinary.com/ewoudtm/image/upload/v1489884984/codaisseurify/bloc_party/bloc-party.jpg", artist: bloc_party)
# photo_the_verve = Photo.create(image: "http://res.cloudinary.com/ewoudtm/image/upload/v1489884774/codaisseurify/verve/1998NMEAwardsVerve021111.jpg", artist: the_verve)
#


#---- Songs ----

#velvet_underground
song1  = Song.create(title: "Sunday Morning", artist: velvet_underground)
song2  = Song.create(title: "Pale Blue Eyes", artist: velvet_underground)
song3  = Song.create(title: "Oh! Sweet Nuthin’", artist: velvet_underground)
song4  = Song.create(title: "Sweet Jane", artist: velvet_underground)
song5  = Song.create(title: "Rock & Roll", artist: velvet_underground)
song6  = Song.create(title: "Venus in Furs", artist: velvet_underground)
song7  = Song.create(title: "Femme Fatale", artist: velvet_underground)
song8  = Song.create(title: "I’m Waiting For The Man", artist: velvet_underground)
song9  = Song.create(title: "Who Loves The Sun", artist: velvet_underground)
song10  = Song.create(title: "Heroin", artist: velvet_underground)
#smashing_pumpkins
song11  = Song.create(title: "1979", artist: smashing_pumpkins)
song12  = Song.create(title: "Bullet With Butterfly Wings", artist: smashing_pumpkins)
song13  = Song.create(title: "Tonight, Tonight", artist: smashing_pumpkins)
song14  = Song.create(title: "Cherub Rock", artist: smashing_pumpkins)
song15  = Song.create(title: "Zero", artist: smashing_pumpkins)
song16  = Song.create(title: "Disarm", artist: smashing_pumpkins)
song17  = Song.create(title: "Today", artist: smashing_pumpkins)
song18  = Song.create(title: "Landslide", artist: smashing_pumpkins)
song19  = Song.create(title: "Mellon Collie and the Infinite Sadness", artist: smashing_pumpkins)
#nirvana
song20  = Song.create(title: "Smells Like Teen Spirit", artist: nirvana)
song21  = Song.create(title: "Come As You Are", artist: nirvana)
song22  = Song.create(title: "Heart-Shaped Box", artist: nirvana)
song23  = Song.create(title: "About A Girl", artist: nirvana)
song24  = Song.create(title: "Lithium", artist: nirvana)
song25  = Song.create(title: "The Man Who Sold The World", artist: nirvana)
song26  = Song.create(title: "Where Did You Sleep Last Night", artist: nirvana)
song27  = Song.create(title: "In Bloom - Nevermind Version", artist: nirvana)
#green_day
song28  = Song.create(title: "Basket Case", artist: green_day)
song29  = Song.create(title: "American Idiot", artist: green_day)
song30  = Song.create(title: "Wake Me Up When September Ends", artist: green_day)
song31  = Song.create(title: "Good Riddance (Time Of Your Life)", artist: green_day)
song32  = Song.create(title: "21 Guns", artist: green_day)
song33  = Song.create(title: "Holiday/Boulevard Of Broken Dreams", artist: green_day)
song34  = Song.create(title: "Still Breathing", artist: green_day)
song35  = Song.create(title: "When I Came Around", artist: green_day)
song36  = Song.create(title: "Bang Bang", artist: green_day)
#rammstein
song37  = Song.create(title: "Du hast", artist: rammstein)
song38  = Song.create(title: "Sonne", artist: rammstein)
song39  = Song.create(title: "Feuer frei", artist: rammstein)
song40  = Song.create(title: "Ich will", artist: rammstein)
song41  = Song.create(title: "AMERIKA", artist: rammstein)
song42  = Song.create(title: "Engel", artist: rammstein)
song43  = Song.create(title: "Mein Herz Brennt", artist: rammstein)
song44  = Song.create(title: "Links 2 3 4", artist: rammstein)
song45  = Song.create(title: "PUSSY", artist: rammstein)
song46  = Song.create(title: "MEIN TEIL", artist: rammstein)
#nick_cave_bad_seeds
song47  = Song.create(title: "Into My Arms", artist: nick_cave_bad_seeds)
song48  = Song.create(title: "Red Right Hand", artist: nick_cave_bad_seeds)
song49  = Song.create(title: "Rings of Saturn", artist: nick_cave_bad_seeds)
song50  = Song.create(title: "Where the Wild Roses Grow", artist: nick_cave_bad_seeds)
song51  = Song.create(title: "I Need You", artist: nick_cave_bad_seeds)
song52  = Song.create(title: "O Children", artist: nick_cave_bad_seeds)
song53  = Song.create(title: "Jesus Alone", artist: nick_cave_bad_seeds)
#david_bowie
song54  = Song.create(title: "Heroes", artist: david_bowie)
song55  = Song.create(title: "Life On Mars?", artist: david_bowie)
song56  = Song.create(title: "Let’s Dance", artist: david_bowie)
song57  = Song.create(title: "Starman", artist: david_bowie)
song58  = Song.create(title: "Under Pressure", artist: david_bowie)
song59  = Song.create(title: "Moonage Daydream", artist: david_bowie)
song60  = Song.create(title: "Rebel Rebel", artist: david_bowie)
#depeche_mode
song61  = Song.create(title: "Enjoy the Silence", artist: depeche_mode)
song62  = Song.create(title: "Personal Jesus", artist: depeche_mode)
song63  = Song.create(title: "World in My Eyes", artist: depeche_mode)
song64  = Song.create(title: "Walking in My Shoes", artist: depeche_mode)
song65  = Song.create(title: "Shake the Disease", artist: depeche_mode)
song66  = Song.create(title: "I Feel You", artist: depeche_mode)
song67  = Song.create(title: "The Sweetest Condition", artist: depeche_mode)
song68  = Song.create(title: "Strangelove", artist: depeche_mode)
song69  = Song.create(title: "People are People", artist: depeche_mode)
#joy_division
song70  = Song.create(title: "Love Will Tear Us Apart", artist: joy_division)
song71  = Song.create(title: "Disorder", artist: joy_division)
song72  = Song.create(title: "She’s Lost Control", artist: joy_division)
song73  = Song.create(title: "Atmosphere", artist: joy_division)
song74  = Song.create(title: "Shadowplay", artist: joy_division)
song75  = Song.create(title: "Transmission", artist: joy_division)
#the_cure
song76  = Song.create(title: "Friday I’m In Love", artist: the_cure)
song77  = Song.create(title: "Boys Don’t Cry", artist: the_cure)
song78  = Song.create(title: "Close To Me", artist: the_cure)
song79  = Song.create(title: "Just Like Heaven", artist: the_cure)
song80  = Song.create(title: "Lullaby", artist: the_cure)
#bloc_party
song81  = Song.create(title: "Banquet", artist: bloc_party)
song82  = Song.create(title: "Helicopter", artist: bloc_party)
song83  = Song.create(title: "Stunt Queen", artist: bloc_party)
song84  = Song.create(title: "This Modern Love", artist: bloc_party)
song85  = Song.create(title: "Flux", artist: bloc_party)
song86  = Song.create(title: "Hunting For Witches", artist: bloc_party)
#the_verve
song87  = Song.create(title: "Bitter Sweet Symphony", artist: the_verve)
song88  = Song.create(title: "The Drugs Don’t Work", artist: the_verve)
song89  = Song.create(title: "Lucky Man", artist: the_verve)
song90  = Song.create(title: "Sonnet", artist: the_verve)
song91  = Song.create(title: "Love Is Noise", artist: the_verve)
